
#! /bin/bash

###########################################
# TypeTE - parameterfile_Ref.init         #
#                                         #
# configuration file for the pipeline     #
#                                         #
# Author: Clement Goubert                 #
# Date: 03/18/2019                        #
# Version: 1.0                            #
###########################################

### MAIN PARAMETERS

## input /!\ USE FULL PATHS HERE /!\

# user data
VCF="/workdir/cg629/Projects/HipSci/ALU_deletion/DEL.final_comp.vcf" #Path to MELT vcf (.vcf or .vcf.gz) must contain INFO field with TSD and MEI type
BAMPATH="/workdir/shared/HipSci_merged_bams" # Path to the bams folder
BAMFILE="/workdir/cg629/Projects/HipSci/HipSci_bamlist.txt" # <indiv_name> <bam_name> (2 fields tab separated table)

# genome data
RM_TRACK="/workdir/cg629/bin//TypeTE/Ressources/RepeatMasker_Alu_hg19.bed" # set by default for hg19
RM_FASTA="/workdir/cg629/bin/TypeTE/Ressources/refinelib" # set by default to be compatible with the Repeat Masker track included in the package

## output
OUTDIR="/workdir/cg629/Projects/HipSci/ALU_deletion" # Path to place the output directory (will be named after PROJECT); OUTDIR must exist
PROJECT="TypeTE.HipSci.Alu" # Name of the project (name of the folder)

### OPTIONS

## mendatory parameters

individual_nb="17" # number of individual per job (try to minimize that number)
CPU="20" # number of CPU (try to maximize that number) # CPU x individual_nb >= total # of individuals
GENOME="/workdir/cg629/Projects/HipSci/refgenome/hg19.1toY.fa" # Path the the reference genome sequence

## non-mendatory parameters
## MAP="NO" #OR NO (experimental)

### DEPENDENCIES PATH
PARALLEL="/programs/parallel/bin/parallel" #Path to the GNU Parallel program
PICARD="/programs/picard-tools-2.9.0" #Path to Picard Tools
BEDTOOLS="/programs/bedtools-2.27.1/bin" #Path to bedtools
SEQTK="/programs/seqtk"
BAMUTILS="/programs/bamUtil"
SPADES="/programs/spades/bin" #Path to spades bin directory (to locate spades.py and dispades.py)
MINIA="/workdir/cg629/bin/minia-v2.0.7-bin-Linux/bin" #Path to minia bin directory
CAP3="/programs/CAP3" #Path to CAP3 directory
BLAST="/programs/ncbi-blast-2.7.1+/bin" #Path to blast bin directory
BWA="/programs/bwa-0.5.9/bwa" #Path to bwa
BGZIP="bgzip" #Path to bgzip
TABIX="tabix" #Path to tabix
# /!\ PERL MUST BE IN PATH /!\
