#! /bin/bash

###########################################
# reGenotypeTE - parameterfile.init       #
#                                         #
# configuration file for the pipeline     #
#                                         #
# Author: Clement Goubert                 #
# Date: 06/2018                           #
# Version: 1.0                            #
###########################################

### MAIN PARAMETERS
## input
# user data
VCF="/ybod/cgoubert/CorrectHet/Del_445_08-30-18/42inds_Del_Lindsay_loci.recode.vcf" #Path to MELT vcf (.vcf or .vcf.gz)
BAMPATH="/vbod2/cgoubert/Correct_Genotypes/1KGP_bams/445_EUR_YRI_Geuvadis" # Path to the bams folder
BAMFILE="/ybod/cgoubert/CorrectHet/Del_445_08-30-18/42_bam_list" # indiv_name bam_name (table 2 fields)
# genome data
RM_TRACK="/home/cgoubert/CorrectHet/reGenotypeTE_del/reGenotypeTE/Ressources/RepeatMasker_Alu_hg19.bed"
RM_FASTA="/home/cgoubert/bin/RepeatMasker/Libraries/dc20170127-rb20170127/homo_sapiens/refinelib"
# output
OUTDIR="/ybod/cgoubert/CorrectHet/Del_445_08-30-18" # Path to place the output directory (will be named after PROJECT); OUTDIR must exist
PROJECT="TEST_Del_42inds_44loc_Lindsay" # Name of the project (name of the folder)

### OPTIONS
## mendatory parameters
#individual_nb="20" # number of individual per job (try to minimize that number)
#CPU="10" # number of CPU (try to maximize that number)
# CPU x individual_nb = total # of individuals
GENOME="/vbod2/cgoubert/Correct_Genotypes/Ref_Genome/genome/hg19.fa" # Path the the reference genome sequence
## non-mendatory parameters
MAP="NO" #OR NO

### DEPENDENCIES PATH
PARALLEL="/usr/bin/parallel" #Path to the GNU Parallel program
PICARD="/home/jainy/software/picard-2.9.2" #Path to Picard Tools
BEDTOOLS="/home/cgoubert/bin/bedtools2/bin" #Path to bedtools
SEQTK="/home/jainy/software/seqtk"
BAMUTILS="/home/jainy/software/bamUtil"
SPADES="/home/jainy/software/SPAdes-3.11.1-Linux/bin" #Path to spades bin directory (to locate spades.py and dispades.py)
MINIA="/home/jainy/software/minia-v2.0.7-Source/build/bin" #Path to minia bin directory
CAP3="/home/jainy/software/CAP3" #Path to CAP3 directory
BLAST="/home/jainy/software/ncbi-blast-2.6.0+/bin" #Path to blast bin directory
BWA="/home/cgoubert/bin/bwa-0.7.16a/bwa" #Path to bwa
BGZIP="/usr/local/bin/bgzip" #Path to bgzip
TABIX="/usr/local/bin/tabix" #Path to tabix
# /!\ PERL MUST BE IN PATH /!\
