#! /bin/bash

###########################################
# TypeTE - parameterfile_Ref.init         #
#                                         #
# configuration file for the pipeline     #
#                                         #
# Author: Clement Goubert                 #
# Date: 03/18/2019                        #
# Version: 1.0                            #
###########################################

### MAIN PARAMETERS

## input /!\ USE FULL PATHS HERE /!\

# user data
VCF="/workdir/shared/HipSci_TE_vcf/Reference-MEI/filtered.maf0.05_vcfs/Alu.HipSci.DEL.final_comp.maf0.05.recode.vcf" #Path to MELT vcf (.vcf or .vcf.gz) must contain INFO field with TSD and MEI type
BAMPATH="/workdir/shared/HipSci_merged_bams" # Path to the bams folder
BAMFILE="/workdir/cg629/bin/SVA.REF.HipSci.beds.txt" # <indiv_name> <bam_name> (2 fields tab separated table)

# genome data
RM_TRACK="/workdir/cg629/bin/TypeTE-SL/Ressources/RepeatMasker_SVA_hg19.bed" # set by default for hg19
RM_FASTA="/workdir/cg629/bin/TypeTE-SL/Ressources/refinelib" # set by default to be compatible with the Repeat Masker track included in the package

## output
OUTDIR="/workdir/cg629/Projects/testTypeTE" # Path to place the output directory (will be named after PROJECT); OUTDIR must exist
PROJECT="SVA.REF.HIPSCI.02192020" # Name of the project (name of the folder)

### OPTIONS

## mendatory parameters

individual_nb="33" # number of individual per job (try to minimize that number)
CPU="10" # number of CPU (try to maximize that number) # CPU x individual_nb >= total # of individuals
GENOME="/workdir/cg629/Projects/HipSci/refgenome/hg19.1toY.fa" # Path the the reference genome sequence

## non-mendatory parameters
## MAP="NO" #OR NO (experimental)

### DEPENDENCIES PATH
