#! /bin/bash

###########################################
# reGenotypeTE - parameterfile.init       #
#                                         #
# configuration file for the pipeline     #
#                                         #
# Author: Clement Goubert                 #
# Date: 07/2018                           #
# Version: 1.0                            #
###########################################

### MAIN PARAMETERS
## input
# user data
VCF="/home/cgoubert/CorrectHet/445_EURO_YRI/ALU-only_discovery_445_EURO_YRI.vcf.recode.vcf" #Path to MELT vcf (.vcf or .vcf.gz) must contain INFO field with TSD and MEI type
BAMPATH="/vbod2/cgoubert/Correct_Genotypes/1KGP_bams/445_EUR_YRI_Geuvadis" # Path to the bams folder
BAMFILE="/home/cgoubert/CorrectHet/445_EURO_YRI/445_bedlist.txt" # <indiv_name> <bam_name> (2 fields tab separated table)
# genome data
RM_TRACK="/home/cgoubert/CorrectHet/reGenotypeTE/Ressources/RepeatMasker_Alu_hg19.bed" # set by default for hg19
RM_FASTA="/home/cgoubert/CorrectHet/reGenotypeTE/Ressources/refinelib" # set by default to be compatible with the Repeat Masker track included in the package
# output
OUTDIR="/ybod/cgoubert/CorrectHet" # Path to place the output directory (will be named after PROJECT); OUTDIR must exist
PROJECT="445_EUR_YRI_corrected_V2_120318" # Name of the project (name of the folder)

### OPTIONS
## mendatory parameters
individual_nb="8" # number of individual per job (try to minimize that number)
CPU="56" # number of CPU (try to maximize that number)
# CPU x individual_nb = total # of individuals
GENOME="/vbod2/cgoubert/Correct_Genotypes/Ref_Genome/genome/hg19.fa" # Path the the reference genome sequence
## non-mendatory parameters
MAP="YES" #OR NO

### DEPENDENCIES PATH
PARALLEL="/usr/bin/parallel" #Path to the GNU Parallel program
PICARD="/home/jainy/software/picard-2.9.2" #Path to Picard Tools
BEDTOOLS="/home/cgoubert/bin/bedtools2/bin" #Path to bedtools
SEQTK="/home/jainy/software/seqtk"
BAMUTILS="/home/jainy/software/bamUtil"
SPADES="/home/jainy/software/SPAdes-3.11.1-Linux/bin" #Path to spades bin directory (to locate spades.py and dispades.py)
MINIA="/home/jainy/software/minia-v2.0.7-Source/build/bin" #Path to minia bin directory
CAP3="/home/jainy/software/CAP3" #Path to CAP3 directory
BLAST="/home/jainy/software/ncbi-blast-2.6.0+/bin" #Path to blast bin directory
BWA="/home/cgoubert/bin/bwa-0.7.16a/bwa" #Path to bwa
BGZIP="/usr/local/bin/bgzip" #Path to bgzip
TABIX="/usr/local/bin/tabix" #Path to tabix
# /!\ PERL MUST BE IN PATH /!\
