#! /bin/bash

###########################################
# reGenotypeTE - parameterfile.init       #
#                                         #
# configuration file for the pipeline     #
#                                         #
# Author: Clement Goubert                 #
# Date: 04/2018                           #
# Version: 1.0                            #
###########################################

### MAIN PARAMETERS
# input
VCF="/home/cgoubert/CorrectHet/ALL.wgs.mergedSV.v8.20130502.svs.genotypes.vcf.gz" #Path to MELT vcf (.vcf or .vcf.gz)
BAMPATH="/vbod2/cgoubert/Correct_Genotypes/1KGP_bams" # Path to the bams' folder
BAMFILE="/vbod2/jainy/SGDP/Project2/findgenotype/1KGP_45_individuals_bams_IDlist.txt" # indiv_name bam_name (table 2 fields)

# output
PROJECT="TEST_1" # Name of the project
OUTDIR="/home/cgoubert/CorrectHet" # Path to place the output directory (will be named after PROJECT); OUTDIR must exist

# mendatory parameters
individual_nb="10" # number of individual per job
CPU="10" # number of CPU
GENOME="" # Paht the the reference genome sequence
MAP="YES" #OR NO
PARALLEL="/usr/bin/parallel" #Path to the GNU Parallel program
$PICARD="/home/jainy/software/picard-2.9.2" #Path to Picard Tools

# non-mendatory parameters


# DEPENDENCIES PATH
