#! /bin/bash

###########################################
# reGenotypeTE - parameterfile.init       #
#                                         #
# configuration file for the pipeline     #
#                                         #
# Author: Clement Goubert                 #
# Date: 08/2018                           #
# Version: 2.0                            #
###########################################

### INPUTS

VCF="/ybod/cgoubert/CorrectHet/SVA/test1/test_SVA.recode.vcf" #Path to MELT vcf (.vcf or .vcf.gz) must contain INFO field with TSD and MEI type
BAMPATH="/vbod2/cgoubert/Correct_Genotypes/1KGP_bams/445_EUR_YRI_Geuvadis/" # Path to the bams folder
BAMFILE="/ybod/cgoubert/CorrectHet/SVA/test1/20_bams.txt" # <indiv_name> <bam_name> (2 fields tab separated table)

### OUTPUTS

OUTDIR="/ybod/cgoubert/CorrectHet/SVA/test1" # Path to place the output directory (will be named after PROJECT); OUTDIR must exist
PROJECT="TEST1" # Name of the project (name of the folder)

### GENOME DATA

GENOME="/vbod2/cgoubert/Correct_Genotypes/Ref_Genome/genome/hg19.fa" # Path the the reference genome sequence
RM_TRACK="/home/cgoubert/CorrectHet/SVA/reGenotypeTE/Ressources/RepeatMasker_SVA_hg19.bed" # set by default for hg19
RM_FASTA="/home/cgoubert/CorrectHet/SVA/reGenotypeTE/Ressources/refinelib" # set by default to be compatible with the Repeat Masker track included in the package


### OPTIONS

individual_nb="1" # number of individual per job (try to minimize that number)
CPU="20" # number of CPU (try to maximize that number)
# CPU x individual_nb = total # of individuals

# Compute mappability score for each locus?
MAP="YES" #YES OR NO; if YES, you need to fill the MYSQL database section of this parameterfile

### MYSQL Database (for mappability score calculation)

DATABASE="jainys_db" # mysql db name
USER="jainy" # mysql user name
PSWD="wysql123" # mysql user password


### DEPENDENCIES PATH
PARALLEL="/usr/bin/parallel" #Path to the GNU Parallel program
PICARD="/home/jainy/software/picard-2.9.2" #Path to Picard Tools
BEDTOOLS="/home/cgoubert/bin/bedtools2/bin" #Path to bedtools
SEQTK="/home/jainy/software/seqtk"
BAMUTILS="/home/jainy/software/bamUtil"
SPADES="/home/jainy/software/SPAdes-3.11.1-Linux/bin" #Path to spades bin directory (to locate spades.py and dispades.py)
MINIA="/home/jainy/software/minia-v2.0.7-Source/build/bin" #Path to minia bin directory
CAP3="/home/jainy/software/CAP3" #Path to CAP3 directory
BLAST="/home/jainy/software/ncbi-blast-2.6.0+/bin" #Path to blast bin directory
BWA="/home/cgoubert/bin/bwa-0.7.16a/bwa" #Path to bwa
BGZIP="/usr/local/bin/bgzip" #Path to bgzip
TABIX="/usr/local/bin/tabix" #Path to tabix
# /!\ PERL MUST BE IN PATH /!\
