#! /bin/bash

###########################################
# TypeTE - parameterfile_Ref.init         #
#                                         #
# configuration file for the pipeline     #
#                                         #
# Author: Clement Goubert                 #
# Date: 03/18/2019                        #
# Version: 2.0.0 (docker)                 #
###########################################

# Chagelog v1 -> v2 adat to docker integration (04/20) 

## input /!\ USE FULL PATHS HERE /!\

### USER DATA
VCF="/workdir/cg629/bin/TypeTE/test_data/test_data_ref.vcf" #Path to MELT vcf (.vcf or .vcf.gz) must contain INFO field with TSD and MEI type
BAMPATH="/workdir/cg629/bin/TypeTE/test_data" # Path to the bams folder
BAMFILE="/workdir/cg629/bin/TypeTE/test_data/test_data_bams.txt" # <indiv_name> <bam_name> (2 fields tab separated table)

### REFERENCE GENOME AND TE TRACK
RM_TRACK="/workdir/cg629/bin//TypeTE/Ressources/RepeatMasker_Alu_hg19.bed" # set by default for hg19
RM_FASTA="/workdir/cg629/bin/TypeTE/Ressources/refinelib" # set by default to be compatible with the Repeat Masker track included in the package

### OUTPUT
OUTDIR="/workdir/cg629/Projects/testTypeTE" # Path to place the output directory (will be named after PROJECT); OUTDIR must exist
PROJECT="TEST_dataREF_ALU" # Name of the project (name of the folder)

### OPTIONS

individual_nb="1" # number of individual per job (try to minimize that number)
CPU="3" # number of CPU (try to maximize that number) # CPU x individual_nb >= total # of individuals
GENOME="/workdir/cg629/Projects/HipSci/refgenome/hs37d5.fa" # Path the the reference genome sequence

### DEPENDENCIES PATH
PARALLEL="parallel" # in path, need exe name
PICARD="/home/TypeTE/softwares/picard" #Path to Picard Tools
BEDTOOLS="" # Bedtool is in path, need folder name
SEQTK="seqtk" # in path, need exe name
BAMUTILS="/home/TypeTE/softwares/bamUtil"
SPADES="" # in path, need folder name
MINIA="" # in path, need folder name
CAP3="" # in path, need folder name
BLAST="" # in path, need folder name
BWA="bwa" # in path, need exe name
BGZIP="bgzip" #Path to bgzip
TABIX="tabix" #Path to tabix
# /!\ PERL MUST BE IN PATH /!\
